##..... structure........###

# total rent ...
# total food .....
# Electricity unit spend ......
# Charge par unit .........
# per person spent .........
#.......total output #............
# total amount spent .......

# total rent ...
rent = int(input("Eneter the total rent amount: " ))

# total food cost .....
food = int(input("Enter the amount spend on food: "))


# Electricity unit spend ......
electricity_spend = int(input("Enter the electricity unit spend: "))

# per unit charge ......
charge_per_unit = int(input("Enter the charge per unit "))

# per person spent .........
person = int(input("Enter the number of persons living in room/flat = "))


# total bill charge per unit 
total_bill = electricity_spend * charge_per_unit

# total amount spent .......
total_spend = ( rent + food + total_bill) // person 

# final output .........
print("total spend per person" , total_spend)
